version: "3.1"

services:
  database:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      # TZ: Tokyo
      # TZ: America/New_York #設定しても何も変わらない
