services:
  - type: web
    # name: wonderful-editor
    name: wonderful-post-app
    env: ruby
    region: singapore
    plan: free
    # plan: starter
    # branch: master
    branch: main
    numInstances: 1
    healthCheckPath: /
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          # name: postgresql-wonderful-editor
          name: postgresql-wonderful-post-app
          property: connectionString
    autoDeploy: false

databases:
  # - name: postgresql-wonderful-editor
  - name: postgresql-wonderful-post-app
    region: singapore
    plan: free
    # plan: starter #有料版にしたから
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere # 学習用
